version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=pass123
      - MYSQL_USER=tasya
      - MYSQL_DATABASE=app

  postgresql:
    image: postgres:14.0
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=tasya
      - POSTGRES_PASSWORD=pass123